version: '2'
services:
  worker:
    build:
      context: .
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin/docker:/usr/local/bin/docker"
    privileged: true
    command: localhost
